apiVersion: v1
kind: Service
metadata:
  name: {{ include "dominium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dominium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dominium.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
